# Colors (Oceanic Next)

# Default colors
[colors.primary]
background = '#1b2b34'
foreground = '#d8dee9'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ec5f67'
green   = '#99c794'
yellow  = '#fac863'
blue    = '#6699cc'
magenta = '#b16286'
cyan    = '#62b3b2'
white   = '#ffffff'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ffffff'

